### ISSUE TITLE
As Pho I want to get reliable data from Discovergy

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#62]
**PR**
- https://github.com/buzzn/admin-app/pull/255
- https://github.com/buzzn/core/pull/1323
---
**Story**
As Pho I want to get reliable data from Discovergy, so I always see correct power and energy values. 

---

**DoD**

- [x] Values retrieved from Disco are converted and returned in Watt for power and Watthour for energy.
- [x] For **one-way meters**, API requests to Discovergy for a given meter retrieve energy, energyOut and power values and assign correctly to register.
- [x] For **two-way meters**, API requests to Discovergy for a given meter retrieve energy, energyOut and power values and assign energy for IN register and energyOut for OUT register of meter.

- [x] I can see the bubble chart for the People Power Group (currently only for this one!) under the "Bubbles" navigation item. The chart shows all consumers and producers as individual bubbles. Note: `?devmode=true` must be added to the URL to enable the navigation

- [x] We can identify registers that are not correctly connected to their data source at Discovergy

excluded: 
-  For **virtual meters**, API requests to Discovergy for a given **virtual** meter retrieve energy, energyOut and power values and assign correctly to register. 
-  updates/changes of group registers are not taken care of
-  create a separate endpoint for the bubble chart

---

**Technical details**

- [x] Cache Discovergy results
- [x] add tests for each case described in DoD
- [x] virtual group: TODO
- [x] adapt frontend

- [x] For **virtual meters**, API requests to Discovergy for a given **virtual** meter retrieve an array of energy, energyOut and power values for all Disco registers included in virtual group. -> test with bubbles on example group: People Power Group

**Comment by dottorer** [comment]
@mkristian @evaklopp Ticket to make DISCO data sources for registers more reliable. Please review DoD and augment where needed.

**Comment by dottorer** [comment]
N

**Comment by mkristian** [comment]
@evaklopp that is actually something for you. a register can be discovergy or not (using some standard profile - Standard Last Profil (SLP)). when discovergy then as I explained today it can be 'broken', i.e. there are no values from discovergy.

here the last DoD to show whether register is connected then I have three cases:
* not a discovergy register (serialNumber given does not exist on discovergy or other reasons)
* is discovergy register
  * is broken no results, no values at all
  * is working

the first case our 'datasource' implementation used to deliver some 'fake' values from the SLP but I am not sure if this is the right thing for PhO

the second case(s) we either have a value to display or not. both can be displayed (somehow). shall there be another indicator like green or red dot somewhere. is it enough if the ticker clearly distinguishes these two cases.

finally shall the ticker be real ticker, i.e. update its number every 15 seconds or so ?

cc/ @dottorer

**Comment by evaklopp** [comment]
@mkristian thanks for explaining. 
From PhOs view we should clearly show if the broker is connected or not. As we design a header for the meter right now, where a user (PhO) should understand if a meter is connected or not, it would be fantastic if we could simply show a red or green dot. If there is the case, that we have your first case, we should display sth like an "!" to show that something is wrong and needs to be chekced? 

What does this ticker looks like? It should be real, but maybe every minute is enough or so?

**Comment by mkristian** [comment]
the first case is a valid case as we have none-discovergy meters. all I wanted to say was that there are fundamentally different then discovergy meters. And there a red or green dot makes no sense, nothing gets connected, all data are prognoses or fake if you want to call it so.

BTW meter and registers are almost the same for me and I keep mixing the terms.

**Comment by evaklopp** [comment]
so we need a "status" for the meters from the first case, that we know that everything is arlright?

**Comment by mkristian** [comment]
not status as this is just an entry in the DB. nothing is connected and reading will come in via someone goes there to manually read the value of the registers. it just should visually look different or just no ticker for them or I do not know.

**Comment by dottorer** [comment]
@mkristian Can you check the DoD and Tech Details that have been completed thus far? If testable, I would like to check it out this morning. Thanks!

**Comment by mkristian** [comment]
@dottorer this is deployed and was done already by https://github.com/buzzn/scrum/issues/29

on Wednesday evening I started this issue and yesterday I just fixed the group->meter->register relations. so I am about to continue on this issue now.

@scsirdx prepared some client code but had not server code to test it against.

**Comment by scsirdx** [comment]
@evaklopp The only way to test it right now is to use devmode and open bubbles for the People Power group. Display app is still broken.

But please wait for the new staging deployment.

**Comment by evaklopp** [comment]
Tell me when staging is ready ;-)

**Comment by mkristian** [comment]
@evaklopp see People Power Group fro bubbles. remember to enable the display-app on the admin-app ;)

**Comment by evaklopp** [comment]
@mkristian @dottorer 
I tested DoD 1 and 4 and it is perfect, great work guys! 
But I don´t know how to test the DoD 2,3 and 5. I have to trust you...Or are there any workarounds?

**Comment by evaklopp** [comment]
@mkristian If you check the Heiglstr. than you have easymeters everywhere but in the ticker of the readings "0" everywhere too. Same in all the other groups like Fritz-WInter-Str. or Gertrud Grunow Str. I couldn´t find any with a number in W.

**Comment by mkristian** [comment]
@evaklopp usually the grid-consumption and grid-feeding registers belong to one two-way meter but for example at `fritz-winter-strasse` I do not think the results are correct but I need to double check here.

**Comment by mkristian** [comment]
nope the two-way meter register tickers are not correct, well one is the other is not.

**Comment by mkristian** [comment]
following problems in bubble endpoints:
Last-Modified is in the future and not in the past.
Expires is a second off
Cache-Control: max-age: 14 but should be 15

some bubbles deliver negative values, due to being a register of two-way meter
some problem with ticker on registers of two-way meters.

**Comment by dottorer** [comment]
Great RCA...I wonder if we always had these issues also in the usage of data in the pre-existing Display App. Guess we never were as deep in the know about details as we are now.

**Comment by mkristian** [comment]
the two-way meter issue were solved (beside some bugs) in the pre-existing code. but now we only have one virtual-meter at Discovergy before we had two so overall logic had two cases for each virtual-meter. I did the two-way meter thing for energy but was unclear until Wednesday about the power thing.

**Comment by evaklopp** [comment]
yeah, great work Kristian! All checked groups worked fine, merry X-Mas, closing!

**Comment by evaklopp** [comment]
yeah, great work Kristian! All checked groups worked fine, merry X-Mas, closing!
